# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            LasershowGen
tagline:          'Laser show editor'
description:      'Free ILDA file and laser show editor.'
url:              http://pages.bitlasers.com

paginate:         2

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde